#! /bin/sh
getent passwd wwwrunner || useradd -mr wwwrunner
sudo -Hu wwwrunner sh -c 'mkdir ~/R'
sudo -Hu wwwrunner sh -c 'echo R_LIBS_USER=~/R > ~/.Renviron'
sudo -Hu wwwrunner Rscript -e "install.packages(pkgs=c('remotes'),lib='~/R')"
sudo -Hu wwwrunner Rscript -e "remotes::install_github(repo=c('tim-band/shinylight','pvermees/simplex'),lib='~/R')"
/usr/local/sbin/updateSimplex.sh
/usr/local/sbin/simplexctl enable
/usr/local/sbin/simplexctl start
systemctl restart nginx
