setwd('~/Documents/Programming/R/simplex/')
source('R/calibrate.R')
source('R/calibration.R')
source('R/drift.R')
source('R/io.R')
source('R/logratios.R')
source('R/method.R')
source('R/pairing.R')
source('R/postprocess.R')
source('R/process.R')
source('R/standard.R')
source('R/toolbox.R')
source('R/trim.R')
source('R/app.R')

shinylight::slStop()
freeformServer(port=8000,test=TRUE,daemonize=FALSE)
